### ISSUE TITLE
Upload New Photos

### ISSUE THREAD

**Issue by sergeyager** [sergeyager/sergeyager.github.io#5]
Photo Criteria:
 - Photos of the pin in use
 - Photos with pin to scale
  * scale meaning next to every day identifiable objects, such as pens, currency, note book, etc

Photos yet to be provided, but here's some direction if we're taking pictures

**Comment by Kimberleydillon** [comment]
Looking for feedback on the photos that Xavier took ( I emailed you them recentlyish)  and wondering if there are new photos you want me to load? 
@sergeyager

**Comment by sergeyager** [comment]
Hey friend,

Sorry for the radio silence. Desert Bus is a hell of a thing.

I appreciate Xavier taking photos, but I don't know if they quite match the feel of what I'm going for.

Here's a folder of photos from my friend TQ: https://drive.google.com/open?id=1HAgGZDzN7MN4S34hfynRQQAuNhLk66lE

**Comment by sergeyager** [comment]
Kimmy had uploaded the photos. They look great.
Closing ticket.
